[package]
name = "playground"
version = "0.0.1"
authors = ["Atmaram Naik <naik.atmaram@gmail.com>"]
edition = "2018"

[dependencies]
rsdb={path="../rsdb"}
rsdb-postgres={path="../rsdb-postgres"}
tokio = {version = "1.10.1", features=["full"]}

